version: '3'
services:
  samson:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GOOGLE_CHAT_ENDPOINT=endpoint
      - DUCKLING_API=http://duckling:8000/parse
    links:
      - duckling
  duckling:
    image: rasa/duckling
    ports:
      - "8000:8000"

duckling:
    image: redis
    ports:
      - "6379:6379"
