version: '3'
services:
  samson:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GOOGLE_CHAT_ENDPOINT=endpoint
      - DUCKLING_API=http://duckling:8000/parse
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USER=
      - REDIS_PASSWORD=
      - RASA_INTENT_API=
    links:
      - duckling
      - redis
  duckling:
    image: rasa/duckling
    ports:
      - "8000:8000"
  redis:
    image: redis
    ports:
      - "6379:6379"
