version: 2
jobs:
  dialyze:
    docker:
      - image: erlang:22
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - rebar-{{ checksum "rebar.lock" }}
      - run: rebar3 dialyzer
      - save_cache:
          paths:
            - ~/repo/_build
          key: rebar-{{ checksum "rebar.lock" }}
  test:
    docker:
      - image: erlang:22
    steps:
      - checkout
      - restore_cache:
          keys:
            - rebar-{{ checksum "rebar.lock" }}
      - run: rebar3 eunit
      - save_cache:
          paths:
            - ~/repo/_build
          key: rebar-{{ checksum "rebar.lock" }}
  deploy_samson_staging:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a samson-chatbot-staging web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a samson-chatbot-staging web
  deploy_duckling_staging:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            cd services/duckling
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a samson-duckling-staging web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a samson-duckling-staging web
  deploy_samson_live:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a samson-chatbot-live web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a samson-chatbot-live web
  deploy_duckling_live:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            cd services/duckling
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a samson-duckling-live web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a samson-duckling-live web

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - dialyze
      - test
      - deploy_samson_staging:
          requires:
            - dialyze
            - test
      - deploy_duckling_staging:
          requires:
            - dialyze
            - test
      - deploy_samson_live:
          requires:
            - deploy_samson_staging
            - deploy_duckling_staging
      - deploy_duckling_live:
          requires:
            - deploy_samson_staging
            - deploy_duckling_staging
