version: 2
jobs:
  build:
    docker:
      - image: erlang:22
    working_directory: ~/repo
    steps:
      - checkout
      - run: rebar3 compile
  test:
    docker:
      - image: erlang:22
    steps:
      - checkout
      - run: rebar3 eunit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
