version: 2
jobs:
  build:
    docker:
      - image: erlang:22
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - rebar-{{ checksum "rebar.lock" }}
      - run: rebar3 compile
      - save_cache:
          paths:
            - ~/repo/_build
          key: rebar-{{ checksum "rebar.lock" }}
  test:
    docker:
      - image: erlang:22
    steps:
      - checkout
      - restore_cache:
          keys:
            - rebar-{{ checksum "rebar.lock" }}
      - run: rebar3 eunit
      - save_cache:
          paths:
            - ~/repo/_build
          key: rebar-{{ checksum "rebar.lock" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
  deploy_staging:
    machine: true
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a samson-chatbot-staging web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a samson-chatbot-staging web

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - deploy_staging:
          requires:
            - build
            - test
