scrape_configs:
  - job_name: samson-staging
    scheme: https
    static_configs:
      - targets: ['samson-chatbot-staging.herokuapp.com']
  - job_name: samson-live
    scheme: https
    static_configs:
      - targets: ['samson-chatbot-live.herokuapp.com']
